@echo off
if "%APPVEYOR_BUILD_FOLDER%" == "" SET APPVEYOR_BUILD_FOLDER=%CD%
if "%APPVEYOR_BUILD_NUMBER%" == "" SET APPVEYOR_BUILD_NUMBER=0
if "%RELEASE_VERSION%" == "" SET RELEASE_VERSION=master
if "%APPVEYOR_REPO_TAG%" == "true" set ARTIFACT_RELEASE_LABEL=%APPVEYOR_REPO_TAG_NAME%
if "%ARTIFACT_RELEASE_LABEL%" == "" SET ARTIFACT_RELEASE_LABEL=master
if "%CONFIGURATION%" == ""  SET CONFIGURATION=Release
if "%PLATFORM%" == "" SET PLATFORM=x64

%APPVEYOR_BUILD_FOLDER%\out\%PLATFORM%\%CONFIGURATION%\FdoTest.exe