platform: Any CPU
configuration: Release
shallow_clone: true
version: 1.4.0.{build}

matrix:
  fast_finish: true

# restore NuGet packages before running MSBuild
before_build:
  - echo CD                             %CD%
  - echo APPVEYOR_PROJECT_NAME          %APPVEYOR_PROJECT_NAME%
  - echo APPVEYOR_PROJECT_SLUG          %APPVEYOR_PROJECT_SLUG%
  - echo APPVEYOR_BUILD_FOLDER          %APPVEYOR_BUILD_FOLDER%
  - echo APPVEYOR_BUILD_ID              %APPVEYOR_BUILD_ID%
  - echo APPVEYOR_BUILD_NUMBER          %APPVEYOR_BUILD_NUMBER%
  - echo APPVEYOR_BUILD_VERSION         %APPVEYOR_BUILD_VERSION%
  - echo APPVEYOR_JOB_ID                %APPVEYOR_JOB_ID%
  - echo APPVEYOR_JOB_NAME              %APPVEYOR_JOB_NAME%
  - echo APPVEYOR_JOB_NUMBER            %APPVEYOR_JOB_NUMBER%
  - echo APPVEYOR_REPO_NAME             %APPVEYOR_REPO_NAME%
  - echo APPVEYOR_REPO_BRANCH           %APPVEYOR_REPO_BRANCH%
  - echo APPVEYOR_REPO_TAG              %APPVEYOR_REPO_TAG%
  - echo APPVEYOR_REPO_TAG_NAME         %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_COMMIT           %APPVEYOR_REPO_COMMIT%
  - echo APPVEYOR_REPO_COMMIT_TIMESTAMP %APPVEYOR_REPO_COMMIT_TIMESTAMP%
  - pip install -U Sphinx
  - nuget update -self
  - nuget restore FdoToolbox.sln
  - echo Stamping version - %APPVEYOR_BUILD_VERSION%
  - SetAssemblyVersion.exe -set:%APPVEYOR_BUILD_VERSION% Properties\GlobalAssemblyInfo.cs


build:
  verbosity: minimal
  parallel: true
  project: FdoToolbox.sln

after_build:
  - set ARTIFACT_RELEASE_LABEL=%APPVEYOR_BUILD_VERSION%
  - appveyor_postbuild.bat

artifacts:
  - path: .\artifacts\MapGuideMaestro-$(configuration)-$(ARTIFACT_RELEASE_LABEL)-Setup.exe
    name: installer_windows

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'Release $(appveyor_repo_tag_name) ($(appveyor_build_version))'
    auth_token:
      secure: Dw0UkS+M9jDa7xofORbKLKgTBWZsBTN56QA7xD7F0pCCdNqnLH3K5oFk3smWjRfX
    artifact: installer_windows
    draft: true
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only