//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FdoToolbox.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FdoToolbox.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Copy Definition.
        /// </summary>
        internal static string DESC_BULK_COPY_DEFINITION {
            get {
                return ResourceManager.GetString("DESC_BULK_COPY_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Definition.
        /// </summary>
        internal static string DESC_JOIN_DEFINITION {
            get {
                return ResourceManager.GetString("DESC_JOIN_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association properties cannot be altered into something else.
        /// </summary>
        internal static string ERR_CANNOT_ALTER_ASSOCIATION {
            get {
                return ResourceManager.GetString("ERR_CANNOT_ALTER_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object properties cannot be altered into something else.
        /// </summary>
        internal static string ERR_CANNOT_ALTER_OBJECT {
            get {
                return ResourceManager.GetString("ERR_CANNOT_ALTER_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create file data source: {0}.
        /// </summary>
        internal static string ERR_CANNOT_CREATE_DATA_FILE {
            get {
                return ResourceManager.GetString("ERR_CANNOT_CREATE_DATA_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate more than once.
        /// </summary>
        internal static string ERR_CANNOT_ENUMERATE_MORE_THAN_ONCE {
            get {
                return ResourceManager.GetString("ERR_CANNOT_ENUMERATE_MORE_THAN_ONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot promote BLOBs.
        /// </summary>
        internal static string ERR_CANNOT_PROMOTE_BLOB {
            get {
                return ResourceManager.GetString("ERR_CANNOT_PROMOTE_BLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot promote CLOBs.
        /// </summary>
        internal static string ERR_CANNOT_PROMOTE_CLOB {
            get {
                return ResourceManager.GetString("ERR_CANNOT_PROMOTE_CLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot promote doubles.
        /// </summary>
        internal static string ERR_CANNOT_PROMOTE_DOUBLE {
            get {
                return ResourceManager.GetString("ERR_CANNOT_PROMOTE_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot promote strings.
        /// </summary>
        internal static string ERR_CANNOT_PROMOTE_STRINGS {
            get {
                return ResourceManager.GetString("ERR_CANNOT_PROMOTE_STRINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is not open.
        /// </summary>
        internal static string ERR_CONNECTION_NOT_OPEN {
            get {
                return ResourceManager.GetString("ERR_CONNECTION_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is in an unknown state.
        /// </summary>
        internal static string ERR_CONNECTION_UNKNOWN_STATE {
            get {
                return ResourceManager.GetString("ERR_CONNECTION_UNKNOWN_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature row has no parent table.
        /// </summary>
        internal static string ERR_FEATURE_ROW_HAS_NO_PARENT_TABLE {
            get {
                return ResourceManager.GetString("ERR_FEATURE_ROW_HAS_NO_PARENT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find incompatible class: {0}.
        /// </summary>
        internal static string ERR_INCOMPATIBLE_CLASS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_INCOMPATIBLE_CLASS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find incompatible property {0} in class {1}.
        /// </summary>
        internal static string ERR_INCOMPATIBLE_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_INCOMPATIBLE_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new feature.
        /// </summary>
        internal static string ERR_INSERT {
            get {
                return ResourceManager.GetString("ERR_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left join source filter is not valid: {0}.
        /// </summary>
        internal static string ERR_INVALID_LEFT_FILTER {
            get {
                return ResourceManager.GetString("ERR_INVALID_LEFT_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right join source filter is not valid: {1}.
        /// </summary>
        internal static string ERR_INVALID_RIGHT_FILTER {
            get {
                return ResourceManager.GetString("ERR_INVALID_RIGHT_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties defined to join both left and right sides on..
        /// </summary>
        internal static string ERR_JOIN_KEYS_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_JOIN_KEYS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left-side join class was not found: {0}.
        /// </summary>
        internal static string ERR_JOIN_LEFT_CLASS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_LEFT_CLASS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find left-side property: {0}.
        /// </summary>
        internal static string ERR_JOIN_LEFT_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_LEFT_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left side of the join has not been defined.
        /// </summary>
        internal static string ERR_JOIN_LEFT_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_JOIN_LEFT_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} in joined class is not a geometry property.
        /// </summary>
        internal static string ERR_JOIN_NOT_TARGET_GEOMETRY_PROPERTY {
            get {
                return ResourceManager.GetString("ERR_JOIN_NOT_TARGET_GEOMETRY_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is at least one or more properties of the same name of both sides of the join. If this is intended, please qualify one side of the join with a prefix..
        /// </summary>
        internal static string ERR_JOIN_PROPERTY_NAME_COLLISION {
            get {
                return ResourceManager.GetString("ERR_JOIN_PROPERTY_NAME_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right-side join class was not found: {0}.
        /// </summary>
        internal static string ERR_JOIN_RIGHT_CLASS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_RIGHT_CLASS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find right-side property: {0}.
        /// </summary>
        internal static string ERR_JOIN_RIGHT_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_RIGHT_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right side of the join has not been defined.
        /// </summary>
        internal static string ERR_JOIN_RIGHT_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_JOIN_RIGHT_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n the join target could not be found.
        /// </summary>
        internal static string ERR_JOIN_SCHEMA_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_SCHEMA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No join target class has been defined.
        /// </summary>
        internal static string ERR_JOIN_TARGET_CLASS_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_JOIN_TARGET_CLASS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The join target must be a feature class that doesn&apos;t already exist.
        /// </summary>
        internal static string ERR_JOIN_TARGET_EXISTS {
            get {
                return ResourceManager.GetString("ERR_JOIN_TARGET_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find geometry property {0} in {1} joined class.
        /// </summary>
        internal static string ERR_JOIN_TARGET_GEOMETRY_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_JOIN_TARGET_GEOMETRY_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join target has not been defined.
        /// </summary>
        internal static string ERR_JOIN_TARGET_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_JOIN_TARGET_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find corresponding Data Type for Type: {0}.
        /// </summary>
        internal static string ERR_NO_CORRESPONDING_DATA_TYPE {
            get {
                return ResourceManager.GetString("ERR_NO_CORRESPONDING_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input defined.
        /// </summary>
        internal static string ERR_NO_INPUT_DEFINED {
            get {
                return ResourceManager.GetString("ERR_NO_INPUT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output defined.
        /// </summary>
        internal static string ERR_NO_OUTPUT_DEFINED {
            get {
                return ResourceManager.GetString("ERR_NO_OUTPUT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset not supported.
        /// </summary>
        internal static string ERR_RESET_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_RESET_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema {0} not found.
        /// </summary>
        internal static string ERR_SCHEMA_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SCHEMA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find mapped property for source expression: {0} =&gt; {1}.
        /// </summary>
        internal static string ERR_SOURCE_EXPRESSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SOURCE_EXPRESSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert class to different type.
        /// </summary>
        internal static string ERR_UNABLE_TO_CONVERT_CLASS {
            get {
                return ResourceManager.GetString("ERR_UNABLE_TO_CONVERT_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a suitable replacement for data type: {0}.
        /// </summary>
        internal static string ERR_UNSUITABLE_DATA_TYPE_REPLACEMENT {
            get {
                return ResourceManager.GetString("ERR_UNSUITABLE_DATA_TYPE_REPLACEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported capability: {0}.
        /// </summary>
        internal static string ERR_UNSUPPORTED_CAPABILITY {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_CAPABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning association properties is currently not supported.
        /// </summary>
        internal static string ERR_UNSUPPORTED_CLONE_ASSOCIATION {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_CLONE_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning this class type {0} is currently not supported.
        /// </summary>
        internal static string ERR_UNSUPPORTED_CLONE_CLASS_TYPE {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_CLONE_CLASS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning object properties is currently not supported.
        /// </summary>
        internal static string ERR_UNSUPPORTED_CLONE_OBJECT {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_CLONE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported command: {0}.
        /// </summary>
        internal static string ERR_UNSUPPORTED_CMD {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy more than one spatial context. Target connection doesn&apos;t support multiple spatial contexts.
        /// </summary>
        internal static string ERR_UNSUPPORTED_COPY_MULTIPLE_SPATIAL_CONTEXTS {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_COPY_MULTIPLE_SPATIAL_CONTEXTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported or Unrecognised FDO Provider.
        /// </summary>
        internal static string ERR_UNSUPPORTED_FLAT_FILE_PROVIDER {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_FLAT_FILE_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection does not support insert commands.
        /// </summary>
        internal static string ERR_UNSUPPORTED_INSERT {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported property type.
        /// </summary>
        internal static string ERR_UNSUPPORTED_PROPERTY_TYPE {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_PROPERTY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection does not support Select Aggregate queries.
        /// </summary>
        internal static string ERR_UNSUPPORTED_SELECT_AGGREGATE {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_SELECT_AGGREGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection does not support SQL queries.
        /// </summary>
        internal static string ERR_UNSUPPORTED_SQL {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating features.
        /// </summary>
        internal static string ERR_UPDATE {
            get {
                return ResourceManager.GetString("ERR_UPDATE", resourceCulture);
            }
        }
    }
}
