//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FdoToolbox.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FdoToolbox.Tasks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bulk Copy.
        /// </summary>
        internal static string CMD_CreateBulkCopy {
            get {
                return ResourceManager.GetString("CMD_CreateBulkCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Join.
        /// </summary>
        internal static string CMD_CreateJoin {
            get {
                return ResourceManager.GetString("CMD_CreateJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sequential Process.
        /// </summary>
        internal static string CMD_CreateSeqProcess {
            get {
                return ResourceManager.GetString("CMD_CreateSeqProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        internal static string CMD_DeleteTask {
            get {
                return ResourceManager.GetString("CMD_DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        internal static string CMD_EditTask {
            get {
                return ResourceManager.GetString("CMD_EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Task.
        /// </summary>
        internal static string CMD_ExecuteTask {
            get {
                return ResourceManager.GetString("CMD_ExecuteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Task.
        /// </summary>
        internal static string CMD_LoadTask {
            get {
                return ResourceManager.GetString("CMD_LoadTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Tasks.
        /// </summary>
        internal static string CMD_RemoveAllTasks {
            get {
                return ResourceManager.GetString("CMD_RemoveAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Task.
        /// </summary>
        internal static string CMD_RenameTask {
            get {
                return ResourceManager.GetString("CMD_RenameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Task.
        /// </summary>
        internal static string CMD_SaveTask {
            get {
                return ResourceManager.GetString("CMD_SaveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute generic ETL process.
        /// </summary>
        internal static string ERR_CANNOT_EXECUTE_UNSPECIALIZED_ETL_PROCESS {
            get {
                return ResourceManager.GetString("ERR_CANNOT_EXECUTE_UNSPECIALIZED_ETL_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} not found in schema {1}.
        /// </summary>
        internal static string ERR_CLASS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CLASS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged class will have duplicate property named: {0}. Either uncheck this property or specify a prefix on the left or right side to differentiate these property names.
        /// </summary>
        internal static string ERR_MERGED_CLASS_DUPLICATE_PROPERTY {
            get {
                return ResourceManager.GetString("ERR_MERGED_CLASS_DUPLICATE_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editor specified for editing this particular task.
        /// </summary>
        internal static string ERR_NO_EDITOR_FOR_TASK {
            get {
                return ResourceManager.GetString("ERR_NO_EDITOR_FOR_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name required.
        /// </summary>
        internal static string ERR_TASK_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_TASK_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Copy Definition (*.BulkCopyDefinition)|*.BulkCopyDefinition|Join Task Definition (*.JoinDefinition)|*.JoinDefinition|Sequential Process  (*.SequentialProcess)|*.SequentialProcess.
        /// </summary>
        internal static string FILTER_TASK_DEFINITION {
            get {
                return ResourceManager.GetString("FILTER_TASK_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find referenced connection. Creating one and adding it to connection manager.
        /// </summary>
        internal static string INFO_REFERENCED_CONNECTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("INFO_REFERENCED_CONNECTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete target.
        /// </summary>
        internal static string LBL_DELETE_TARGET {
            get {
                return ResourceManager.GetString("LBL_DELETE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source class filter.
        /// </summary>
        internal static string LBL_SOURCE_FILTER {
            get {
                return ResourceManager.GetString("LBL_SOURCE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading task definition. Please wait..
        /// </summary>
        internal static string LOADING_TASK_DEFINITION_WAIT {
            get {
                return ResourceManager.GetString("LOADING_TASK_DEFINITION_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        internal static string MENU_NEW_TASK {
            get {
                return ResourceManager.GetString("MENU_NEW_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete is not supported.
        /// </summary>
        internal static string MSG_DELETE_UNSUPPORTED {
            get {
                return ResourceManager.GetString("MSG_DELETE_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task saved to {0}.
        /// </summary>
        internal static string MSG_TASK_SAVED {
            get {
                return ResourceManager.GetString("MSG_TASK_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Computed Properties.
        /// </summary>
        internal static string NODE_EXPRESSION {
            get {
                return ResourceManager.GetString("NODE_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Copy Options.
        /// </summary>
        internal static string NODE_OPTIONS {
            get {
                return ResourceManager.GetString("NODE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Properties.
        /// </summary>
        internal static string NODE_PROPERTIES {
            get {
                return ResourceManager.GetString("NODE_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name for the task.
        /// </summary>
        internal static string PROMPT_ENTER_NEW_TASK_NAME {
            get {
                return ResourceManager.GetString("PROMPT_ENTER_NEW_TASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Copy Settings.
        /// </summary>
        internal static string TITLE_BULK_COPY_SETTINGS {
            get {
                return ResourceManager.GetString("TITLE_BULK_COPY_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Directory.
        /// </summary>
        internal static string TITLE_CHOOSE_DIRECTORY {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running ETL Process.
        /// </summary>
        internal static string TITLE_ETL_PROCESS {
            get {
                return ResourceManager.GetString("TITLE_ETL_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Settings.
        /// </summary>
        internal static string TITLE_JOIN_SETTINGS {
            get {
                return ResourceManager.GetString("TITLE_JOIN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Task.
        /// </summary>
        internal static string TITLE_LOAD_TASK {
            get {
                return ResourceManager.GetString("TITLE_LOAD_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Task.
        /// </summary>
        internal static string TITLE_RENAME_TASK {
            get {
                return ResourceManager.GetString("TITLE_RENAME_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Task.
        /// </summary>
        internal static string TITLE_SAVE_TASK {
            get {
                return ResourceManager.GetString("TITLE_SAVE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of join to perform.
        /// </summary>
        internal static string TOOLTIP_JOIN_TYPE {
            get {
                return ResourceManager.GetString("TOOLTIP_JOIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix to attach to property names in merged features that come from the left side of the join.
        /// </summary>
        internal static string TOOLTIP_LEFT_PREFIX {
            get {
                return ResourceManager.GetString("TOOLTIP_LEFT_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix to attach to property names in merged features that come from the right side of the join.
        /// </summary>
        internal static string TOOLTIP_RIGHT_PREFIX {
            get {
                return ResourceManager.GetString("TOOLTIP_RIGHT_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spatial condition to join left and right sides on.
        /// </summary>
        internal static string TOOLTIP_SPATIAL_PREDICATE {
            get {
                return ResourceManager.GetString("TOOLTIP_SPATIAL_PREDICATE", resourceCulture);
            }
        }
    }
}
