//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FdoToolbox.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FdoToolbox.Base.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses the following thirdparty libraries and resources:
        ///
        ///- SharpDevelop Core (c) ic#code (http://www.icsharpcode.com/OpenSource/SD/Default.aspx)
        ///- Feature Data Objects (c) Autodesk/OSGeo (http://fdo.osgeo.org)
        ///- DockPanel Suite (c) Weifen Luo (http://sourceforge.net/projects/dockpanelsuite)
        ///- famfamfam silk icon set (c) Mark James (http://www.famfamfam.com/lab/icons/silk/)
        ///- Iesi.Collections (c) Jason Smith
        ///- SharpMap 0.9 (c) Morten Nielsen (http://www.codeplex.com/SharpMap)
        ///- C# Spa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APP_ABOUT {
            get {
                return ResourceManager.GetString("APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackie Ng.
        /// </summary>
        internal static string APP_AUTHOR {
            get {
                return ResourceManager.GetString("APP_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jumpinjackie@gmail.com.
        /// </summary>
        internal static string APP_AUTHOR_EMAIL {
            get {
                return ResourceManager.GetString("APP_AUTHOR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fdotoolbox.googlecode.com.
        /// </summary>
        internal static string APP_PROJECT_URL {
            get {
                return ResourceManager.GetString("APP_PROJECT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About FDO Toolbox.
        /// </summary>
        internal static string CMD_About {
            get {
                return ResourceManager.GetString("CMD_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In Manager.
        /// </summary>
        internal static string CMD_AddInManager {
            get {
                return ResourceManager.GetString("CMD_AddInManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core API Documentation.
        /// </summary>
        internal static string CMD_ApiHelp {
            get {
                return ResourceManager.GetString("CMD_ApiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Delete.
        /// </summary>
        internal static string CMD_BulkDelete {
            get {
                return ResourceManager.GetString("CMD_BulkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Update.
        /// </summary>
        internal static string CMD_BulkUpdate {
            get {
                return ResourceManager.GetString("CMD_BulkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Console.
        /// </summary>
        internal static string CMD_Clear {
            get {
                return ResourceManager.GetString("CMD_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Data.
        /// </summary>
        internal static string CMD_Connect {
            get {
                return ResourceManager.GetString("CMD_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate System Catalog.
        /// </summary>
        internal static string CMD_CoordSysCatalog {
            get {
                return ResourceManager.GetString("CMD_CoordSysCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Store.
        /// </summary>
        internal static string CMD_CreateDataStore {
            get {
                return ResourceManager.GetString("CMD_CreateDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Schema.
        /// </summary>
        internal static string CMD_CreateSchema {
            get {
                return ResourceManager.GetString("CMD_CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Query.
        /// </summary>
        internal static string CMD_DataPreview {
            get {
                return ResourceManager.GetString("CMD_DataPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Schema.
        /// </summary>
        internal static string CMD_DeleteSchema {
            get {
                return ResourceManager.GetString("CMD_DeleteSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Class Attributes.
        /// </summary>
        internal static string CMD_EditClassAttributes {
            get {
                return ResourceManager.GetString("CMD_EditClassAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schema Attributes.
        /// </summary>
        internal static string CMD_EditSchemaAttributes {
            get {
                return ResourceManager.GetString("CMD_EditSchemaAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SQL.
        /// </summary>
        internal static string CMD_ExecuteSql {
            get {
                return ResourceManager.GetString("CMD_ExecuteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CMD_Exit {
            get {
                return ResourceManager.GetString("CMD_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data Store Configuration to XML.
        /// </summary>
        internal static string CMD_ExportDataStoreXml {
            get {
                return ResourceManager.GetString("CMD_ExportDataStoreXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Contents.
        /// </summary>
        internal static string CMD_Help {
            get {
                return ResourceManager.GetString("CMD_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Data.
        /// </summary>
        internal static string CMD_InsertData {
            get {
                return ResourceManager.GetString("CMD_InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert New Feature.
        /// </summary>
        internal static string CMD_InsertFeature {
            get {
                return ResourceManager.GetString("CMD_InsertFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Connection.
        /// </summary>
        internal static string CMD_LoadConnection {
            get {
                return ResourceManager.GetString("CMD_LoadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Data Stores.
        /// </summary>
        internal static string CMD_ManageDataStores {
            get {
                return ResourceManager.GetString("CMD_ManageDataStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Spatial Contexts.
        /// </summary>
        internal static string CMD_ManageSpatialContexts {
            get {
                return ResourceManager.GetString("CMD_ManageSpatialContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open FDO Directory.
        /// </summary>
        internal static string CMD_OpenFdoDir {
            get {
                return ResourceManager.GetString("CMD_OpenFdoDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Directory.
        /// </summary>
        internal static string CMD_OpenLogsDir {
            get {
                return ResourceManager.GetString("CMD_OpenLogsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Session Directory.
        /// </summary>
        internal static string CMD_OpenSessionDir {
            get {
                return ResourceManager.GetString("CMD_OpenSessionDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string CMD_Preferences {
            get {
                return ResourceManager.GetString("CMD_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Connection.
        /// </summary>
        internal static string CMD_RefreshConnection {
            get {
                return ResourceManager.GetString("CMD_RefreshConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Provider.
        /// </summary>
        internal static string CMD_RegProvider {
            get {
                return ResourceManager.GetString("CMD_RegProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Connections.
        /// </summary>
        internal static string CMD_RemoveAllConnections {
            get {
                return ResourceManager.GetString("CMD_RemoveAllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Connection.
        /// </summary>
        internal static string CMD_RemoveConnection {
            get {
                return ResourceManager.GetString("CMD_RemoveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Connection.
        /// </summary>
        internal static string CMD_RenameConnection {
            get {
                return ResourceManager.GetString("CMD_RenameConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Connection.
        /// </summary>
        internal static string CMD_SaveConnection {
            get {
                return ResourceManager.GetString("CMD_SaveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Console Log.
        /// </summary>
        internal static string CMD_SaveLog {
            get {
                return ResourceManager.GetString("CMD_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Schema.
        /// </summary>
        internal static string CMD_SaveSchema {
            get {
                return ResourceManager.GetString("CMD_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Manager.
        /// </summary>
        internal static string CMD_ScriptManager {
            get {
                return ResourceManager.GetString("CMD_ScriptManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string CMD_TextEditor {
            get {
                return ResourceManager.GetString("CMD_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister Provider.
        /// </summary>
        internal static string CMD_UnregProvider {
            get {
                return ResourceManager.GetString("CMD_UnregProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Capabilities.
        /// </summary>
        internal static string CMD_ViewCapabilites {
            get {
                return ResourceManager.GetString("CMD_ViewCapabilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter schema failed.
        /// </summary>
        internal static string ERR_FAIL_ALTER_SCHEMA {
            get {
                return ResourceManager.GetString("ERR_FAIL_ALTER_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string ERR_FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No query result to save!.
        /// </summary>
        internal static string ERR_NO_RESULT_TABLE_TO_SAVE {
            get {
                return ResourceManager.GetString("ERR_NO_RESULT_TABLE_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply schema: {0}.
        /// </summary>
        internal static string ERR_SCHEMA_CANNOT_BE_APPLIED {
            get {
                return ResourceManager.GetString("ERR_SCHEMA_CANNOT_BE_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema contains zero-length string/blob/clob properties: {0}.
        /// </summary>
        internal static string ERR_SCHEMA_ZERO_LENGTH_PROPERTIES {
            get {
                return ResourceManager.GetString("ERR_SCHEMA_ZERO_LENGTH_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save schema changes.
        /// </summary>
        internal static string ERR_UNABLE_TO_SAVE_SCHEMAS {
            get {
                return ResourceManager.GetString("ERR_UNABLE_TO_SAVE_SCHEMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection doesn&apos;t support SQL commands.
        /// </summary>
        internal static string ERR_UNSUPPORTED_SQL {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load ${File}. File not found..
        /// </summary>
        internal static string FileUtility_CantFindFileError {
            get {
                return ResourceManager.GetString("FileUtility.CantFindFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading.
        /// </summary>
        internal static string FileUtilityService_ErrorWhileLoading {
            get {
                return ResourceManager.GetString("FileUtilityService.ErrorWhileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        internal static string FileUtilityService_ErrorWhileSaving {
            get {
                return ResourceManager.GetString("FileUtilityService.ErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string FILTER_ALL {
            get {
                return ResourceManager.GetString("FILTER_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings (*.conn)|*.conn.
        /// </summary>
        internal static string FILTER_CONNECTION_FILE {
            get {
                return ResourceManager.GetString("FILTER_CONNECTION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDO Library (*.dll)|*.dll.
        /// </summary>
        internal static string FILTER_DLL {
            get {
                return ResourceManager.GetString("FILTER_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files (*.log)|*.log.
        /// </summary>
        internal static string FILTER_LOG_FILE {
            get {
                return ResourceManager.GetString("FILTER_LOG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDO Data Store Configuration (*.xml)|*.xml|FDO Feature Schema (*.schema)|*.schema.
        /// </summary>
        internal static string FILTER_SCHEMA_FILE {
            get {
                return ResourceManager.GetString("FILTER_SCHEMA_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDF Files (*.sdf)|*.sdf.
        /// </summary>
        internal static string FILTER_SDF_FILE {
            get {
                return ResourceManager.GetString("FILTER_SDF_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP Files (*.shp)|*.shp.
        /// </summary>
        internal static string FILTER_SHP {
            get {
                return ResourceManager.GetString("FILTER_SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string FILTER_XML_FILES {
            get {
                return ResourceManager.GetString("FILTER_XML_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string Global_AddButtonText {
            get {
                return ResourceManager.GetString("Global.AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Global_BackButtonText {
            get {
                return ResourceManager.GetString("Global.BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse.
        /// </summary>
        internal static string Global_BrowseButtonText {
            get {
                return ResourceManager.GetString("Global.BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Global_BrowseText {
            get {
                return ResourceManager.GetString("Global.BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Global_CancelButtonText {
            get {
                return ResourceManager.GetString("Global.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Change.
        /// </summary>
        internal static string Global_ChangeButtonText {
            get {
                return ResourceManager.GetString("Global.ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        internal static string Global_ChooseLocationButtonText {
            get {
                return ResourceManager.GetString("Global.ChooseLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Global_CloseButtonText {
            get {
                return ResourceManager.GetString("Global.CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Global_CreateButtonText {
            get {
                return ResourceManager.GetString("Global.CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Global_DeleteButtonText {
            get {
                return ResourceManager.GetString("Global.DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Global_EditButtonText {
            get {
                return ResourceManager.GetString("Global.EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Global_ErrorText {
            get {
                return ResourceManager.GetString("Global.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Global_FinishButtonText {
            get {
                return ResourceManager.GetString("Global.FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Global_FinishedCaptionText {
            get {
                return ResourceManager.GetString("Global.FinishedCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Global_HelpButtonText {
            get {
                return ResourceManager.GetString("Global.HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Global_IgnoreButtonText {
            get {
                return ResourceManager.GetString("Global.IgnoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icons.
        /// </summary>
        internal static string Global_LargeIconToolTip {
            get {
                return ResourceManager.GetString("Global.LargeIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Global_NextButtonText {
            get {
                return ResourceManager.GetString("Global.NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Global_OKButtonText {
            get {
                return ResourceManager.GetString("Global.OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string Global_OpenButtonText {
            get {
                return ResourceManager.GetString("Global.OpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Global_QuestionText {
            get {
                return ResourceManager.GetString("Global.QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string Global_RemoveButtonText {
            get {
                return ResourceManager.GetString("Global.RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string Global_RetryButtonText {
            get {
                return ResourceManager.GetString("Global.RetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icons.
        /// </summary>
        internal static string Global_SmallIconToolTip {
            get {
                return ResourceManager.GetString("Global.SmallIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Global_StartButtonText {
            get {
                return ResourceManager.GetString("Global.StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string Global_UpdateButtonText {
            get {
                return ResourceManager.GetString("Global.UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Global_WarningText {
            get {
                return ResourceManager.GetString("Global.WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ICSharpCode_Core_Services_ErrorDialogs_DescriptionLabel {
            get {
                return ResourceManager.GetString("ICSharpCode.Core.Services.ErrorDialogs.DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception got.
        /// </summary>
        internal static string ICSharpCode_Core_Services_ErrorDialogs_ExceptionGotDescription {
            get {
                return ResourceManager.GetString("ICSharpCode.Core.Services.ErrorDialogs.ExceptionGotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exception.
        /// </summary>
        internal static string ICSharpCode_Core_Services_ErrorDialogs_ShowExceptionButton {
            get {
                return ResourceManager.GetString("ICSharpCode.Core.Services.ErrorDialogs.ShowExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Property.
        /// </summary>
        internal static string LBL_ASSOCIATION_PROPERTY {
            get {
                return ResourceManager.GetString("LBL_ASSOCIATION_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string LBL_CLASS {
            get {
                return ResourceManager.GetString("LBL_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Property.
        /// </summary>
        internal static string LBL_DATA_PROPERTY {
            get {
                return ResourceManager.GetString("LBL_DATA_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Class.
        /// </summary>
        internal static string LBL_FEATURE_CLASS {
            get {
                return ResourceManager.GetString("LBL_FEATURE_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Schema.
        /// </summary>
        internal static string LBL_FEATURE_SCHEMA {
            get {
                return ResourceManager.GetString("LBL_FEATURE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Property.
        /// </summary>
        internal static string LBL_GEOMETRIC_PROPERTY {
            get {
                return ResourceManager.GetString("LBL_GEOMETRIC_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Property.
        /// </summary>
        internal static string LBL_OBJECT_PROPERTY {
            get {
                return ResourceManager.GetString("LBL_OBJECT_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema {0} deleted from connection: {1}.
        /// </summary>
        internal static string LOG_SCHEMA_DELETED {
            get {
                return ResourceManager.GetString("LOG_SCHEMA_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas saved to {0}.
        /// </summary>
        internal static string LOG_SCHEMA_SAVED {
            get {
                return ResourceManager.GetString("LOG_SCHEMA_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema {0} saved to {1}.
        /// </summary>
        internal static string LOG_SCHEMA_SAVED_2 {
            get {
                return ResourceManager.GetString("LOG_SCHEMA_SAVED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been applied.
        /// </summary>
        internal static string MSG_CHANGES_APPLIED {
            get {
                return ResourceManager.GetString("MSG_CHANGES_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this spatial context will delete *all* data stored in this context. Are you sure you want to do this?.
        /// </summary>
        internal static string MSG_CONFIRM_DELETE_SPATIAL_CONTEXT {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE_SPATIAL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data store created..
        /// </summary>
        internal static string MSG_DATA_STORE_CREATED {
            get {
                return ResourceManager.GetString("MSG_DATA_STORE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} errors were encountered when running this ETL process..
        /// </summary>
        internal static string MSG_ETL_ERRORS {
            get {
                return ResourceManager.GetString("MSG_ETL_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema is incompatible and cannot be applied. {0} Attempt to fix it?.
        /// </summary>
        internal static string MSG_INCOMPATIBLE_SCHEMA {
            get {
                return ResourceManager.GetString("MSG_INCOMPATIBLE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing all Data Stores.
        /// </summary>
        internal static string MSG_LISTING_DATA_STORES {
            get {
                return ResourceManager.GetString("MSG_LISTING_DATA_STORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing all Spatial Contexts in Data Source.
        /// </summary>
        internal static string MSG_LISTING_SPATIAL_CONTEXTS {
            get {
                return ResourceManager.GetString("MSG_LISTING_SPATIAL_CONTEXTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences saved.
        /// </summary>
        internal static string MSG_PREFS_SAVED {
            get {
                return ResourceManager.GetString("MSG_PREFS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider registered.
        /// </summary>
        internal static string MSG_PROVIDER_REGISTERED {
            get {
                return ResourceManager.GetString("MSG_PROVIDER_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider un-registered.
        /// </summary>
        internal static string MSG_PROVIDER_UNREGISTERED {
            get {
                return ResourceManager.GetString("MSG_PROVIDER_UNREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the class name for this result table.
        /// </summary>
        internal static string MSG_SAVE_QUERY_AS {
            get {
                return ResourceManager.GetString("MSG_SAVE_QUERY_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Applied.
        /// </summary>
        internal static string MSG_SCHEMA_APPLIED {
            get {
                return ResourceManager.GetString("MSG_SCHEMA_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Deleted.
        /// </summary>
        internal static string MSG_SCHEMA_DELETED {
            get {
                return ResourceManager.GetString("MSG_SCHEMA_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas loaded into connection {0} from {1}.
        /// </summary>
        internal static string MSG_SCHEMA_LOADED {
            get {
                return ResourceManager.GetString("MSG_SCHEMA_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Saved.
        /// </summary>
        internal static string MSG_SCHEMA_SAVED {
            get {
                return ResourceManager.GetString("MSG_SCHEMA_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the classes to compute the extents from.
        /// </summary>
        internal static string MSG_SELECT_EXTENT_CLASSES {
            get {
                return ResourceManager.GetString("MSG_SELECT_EXTENT_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a spatial context from the list below.
        /// </summary>
        internal static string MSG_SELECT_SPATIAL_CONTEXT {
            get {
                return ResourceManager.GetString("MSG_SELECT_SPATIAL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Context Created.
        /// </summary>
        internal static string MSG_SPATIAL_CONTEXT_CREATED {
            get {
                return ResourceManager.GetString("MSG_SPATIAL_CONTEXT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Context Updated.
        /// </summary>
        internal static string MSG_SPATIAL_CONTEXT_UPDATED {
            get {
                return ResourceManager.GetString("MSG_SPATIAL_CONTEXT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is valid.
        /// </summary>
        internal static string MSG_VALID_EXPRESSION {
            get {
                return ResourceManager.GetString("MSG_VALID_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name for the connection.
        /// </summary>
        internal static string PROMPT_ENTER_NEW_CONNECTION_NAME {
            get {
                return ResourceManager.GetString("PROMPT_ENTER_NEW_CONNECTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close a connection named {0} that some open tabs depend on. Are you sure you want to continue?.
        /// </summary>
        internal static string QUESTION_CLOSE_TABS {
            get {
                return ResourceManager.GetString("QUESTION_CLOSE_TABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your query will be returning {0} results. Do you want to continue..
        /// </summary>
        internal static string QUESTION_DATA_PREVIEW_LIMIT {
            get {
                return ResourceManager.GetString("QUESTION_DATA_PREVIEW_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save now?.
        /// </summary>
        internal static string QUESTION_UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("QUESTION_UNSAVED_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string TEXT_LOADING {
            get {
                return ResourceManager.GetString("TEXT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Delete.
        /// </summary>
        internal static string TITLE_BULK_DELETE {
            get {
                return ResourceManager.GetString("TITLE_BULK_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Update.
        /// </summary>
        internal static string TITLE_BULK_UPDATE {
            get {
                return ResourceManager.GetString("TITLE_BULK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Update Features.
        /// </summary>
        internal static string TITLE_BULK_UPDATE_FEATURE {
            get {
                return ResourceManager.GetString("TITLE_BULK_UPDATE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities.
        /// </summary>
        internal static string TITLE_CAPABILITIES {
            get {
                return ResourceManager.GetString("TITLE_CAPABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Extents.
        /// </summary>
        internal static string TITLE_COMPUTE_EXTENTS {
            get {
                return ResourceManager.GetString("TITLE_COMPUTE_EXTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Spatial Context.
        /// </summary>
        internal static string TITLE_CONFIRM_DELETE_SPATIAL_CONTEXT {
            get {
                return ResourceManager.GetString("TITLE_CONFIRM_DELETE_SPATIAL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate System.
        /// </summary>
        internal static string TITLE_COORDINATE_SYSTEM {
            get {
                return ResourceManager.GetString("TITLE_COORDINATE_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate System Catalog.
        /// </summary>
        internal static string TITLE_COORDSYS_CATALOG {
            get {
                return ResourceManager.GetString("TITLE_COORDSYS_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Store.
        /// </summary>
        internal static string TITLE_CREATE_DATA_STORE {
            get {
                return ResourceManager.GetString("TITLE_CREATE_DATA_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Store.
        /// </summary>
        internal static string TITLE_CREATE_DATASTORE {
            get {
                return ResourceManager.GetString("TITLE_CREATE_DATASTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Spatial Context.
        /// </summary>
        internal static string TITLE_CREATE_SPATIAL_CONTEXT {
            get {
                return ResourceManager.GetString("TITLE_CREATE_SPATIAL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Query.
        /// </summary>
        internal static string TITLE_DATA_PREVIEW {
            get {
                return ResourceManager.GetString("TITLE_DATA_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Management.
        /// </summary>
        internal static string TITLE_DATA_STORE_MGMT {
            get {
                return ResourceManager.GetString("TITLE_DATA_STORE_MGMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Schema.
        /// </summary>
        internal static string TITLE_DELETE_SCHEMA {
            get {
                return ResourceManager.GetString("TITLE_DELETE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Data Store.
        /// </summary>
        internal static string TITLE_DESTROY_DATASTORE {
            get {
                return ResourceManager.GetString("TITLE_DESTROY_DATASTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Class Attributes.
        /// </summary>
        internal static string TITLE_EDIT_CLASS_ATTRIBUTES {
            get {
                return ResourceManager.GetString("TITLE_EDIT_CLASS_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schema Attributes.
        /// </summary>
        internal static string TITLE_EDIT_SCHEMA_ATTRIBUTES {
            get {
                return ResourceManager.GetString("TITLE_EDIT_SCHEMA_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data Store Configuration.
        /// </summary>
        internal static string TITLE_EXPORT_DATASTORE_XML {
            get {
                return ResourceManager.GetString("TITLE_EXPORT_DATASTORE_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Editor.
        /// </summary>
        internal static string TITLE_EXPRESSION_EDITOR {
            get {
                return ResourceManager.GetString("TITLE_EXPRESSION_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert New Feature.
        /// </summary>
        internal static string TITLE_INSERT_FEATURE {
            get {
                return ResourceManager.GetString("TITLE_INSERT_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration file.
        /// </summary>
        internal static string TITLE_LOAD_CONFIGURATION {
            get {
                return ResourceManager.GetString("TITLE_LOAD_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Connection.
        /// </summary>
        internal static string TITLE_LOAD_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_LOAD_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Feature Schema.
        /// </summary>
        internal static string TITLE_LOAD_SCHEMA {
            get {
                return ResourceManager.GetString("TITLE_LOAD_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        internal static string TITLE_NEW_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_NEW_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Connection.
        /// </summary>
        internal static string TITLE_NEW_DATA_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_NEW_DATA_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string TITLE_OPEN_FILE {
            get {
                return ResourceManager.GetString("TITLE_OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Additional Parameters.
        /// </summary>
        internal static string TITLE_PENDING_PARAMETERS {
            get {
                return ResourceManager.GetString("TITLE_PENDING_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string TITLE_PREFERENCES {
            get {
                return ResourceManager.GetString("TITLE_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Preview.
        /// </summary>
        internal static string TITLE_PREFS_DATA_PREVIEW {
            get {
                return ResourceManager.GetString("TITLE_PREFS_DATA_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TITLE_PREFS_GENERAL {
            get {
                return ResourceManager.GetString("TITLE_PREFS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Engine.
        /// </summary>
        internal static string TITLE_PREFS_SCRIPT {
            get {
                return ResourceManager.GetString("TITLE_PREFS_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Provider.
        /// </summary>
        internal static string TITLE_REGISTER_PROVIDER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Connection.
        /// </summary>
        internal static string TITLE_RENAME_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_RENAME_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Connection.
        /// </summary>
        internal static string TITLE_SAVE_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_SAVE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string TITLE_SAVE_FILE {
            get {
                return ResourceManager.GetString("TITLE_SAVE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        internal static string TITLE_SAVE_LOG {
            get {
                return ResourceManager.GetString("TITLE_SAVE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Query.
        /// </summary>
        internal static string TITLE_SAVE_QUERY_AS {
            get {
                return ResourceManager.GetString("TITLE_SAVE_QUERY_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Query Result.
        /// </summary>
        internal static string TITLE_SAVE_QUERY_RESULT {
            get {
                return ResourceManager.GetString("TITLE_SAVE_QUERY_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Feature Schema.
        /// </summary>
        internal static string TITLE_SAVE_SCHEMA {
            get {
                return ResourceManager.GetString("TITLE_SAVE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Designer.
        /// </summary>
        internal static string TITLE_SCHEMA_DESIGNER {
            get {
                return ResourceManager.GetString("TITLE_SCHEMA_DESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Information.
        /// </summary>
        internal static string TITLE_SCHEMA_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_SCHEMA_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Management.
        /// </summary>
        internal static string TITLE_SCHEMA_MANAGEMENT {
            get {
                return ResourceManager.GetString("TITLE_SCHEMA_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        internal static string TITLE_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("TITLE_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Context Browser.
        /// </summary>
        internal static string TITLE_SPATIAL_CONTEXT_BROWSER {
            get {
                return ResourceManager.GetString("TITLE_SPATIAL_CONTEXT_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Context Management.
        /// </summary>
        internal static string TITLE_SPATIAL_CONTEXT_MGMT {
            get {
                return ResourceManager.GetString("TITLE_SPATIAL_CONTEXT_MGMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string TITLE_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("TITLE_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Register Provider.
        /// </summary>
        internal static string TITLE_UNREGISTER_PROVIDER {
            get {
                return ResourceManager.GetString("TITLE_UNREGISTER_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Feature.
        /// </summary>
        internal static string TITLE_UPDATE_FEATURE {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Spatial Context.
        /// </summary>
        internal static string TITLE_UPDATE_SPATIAL_CONTEXT {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_SPATIAL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Expression.
        /// </summary>
        internal static string TITLE_VALIDATE_EXPRESSION {
            get {
                return ResourceManager.GetString("TITLE_VALIDATE_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand.
        /// </summary>
        internal static string TT_EXPAND {
            get {
                return ResourceManager.GetString("TT_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Console.
        /// </summary>
        internal static string UI_CONSOLE {
            get {
                return ResourceManager.GetString("UI_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Explorer.
        /// </summary>
        internal static string UI_OBJECT_EXPLORER {
            get {
                return ResourceManager.GetString("UI_OBJECT_EXPLORER", resourceCulture);
            }
        }
    }
}
