//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FdoToolbox.DataStoreManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FdoToolbox.DataStoreManager.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Editor.
        /// </summary>
        internal static string CMD_DataStoreEditor {
            get {
                return ResourceManager.GetString("CMD_DataStoreEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data Store.
        /// </summary>
        internal static string CMD_EditDataStore {
            get {
                return ResourceManager.GetString("CMD_EditDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Schema Mappings.
        /// </summary>
        internal static string CMD_ManageSchemaMappings {
            get {
                return ResourceManager.GetString("CMD_ManageSchemaMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Mappings for this provider are not supported.
        /// </summary>
        internal static string ERR_SCHEMA_MAPPING_UNSUPPORTED_PROVIDER {
            get {
                return ResourceManager.GetString("ERR_SCHEMA_MAPPING_UNSUPPORTED_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Editor.
        /// </summary>
        internal static string TITLE_DATA_STORE {
            get {
                return ResourceManager.GetString("TITLE_DATA_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Editor (Standalone).
        /// </summary>
        internal static string TITLE_DATA_STORE_STANDALONE {
            get {
                return ResourceManager.GetString("TITLE_DATA_STORE_STANDALONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Overrides.
        /// </summary>
        internal static string TITLE_SCHEMA_OVERRIDES {
            get {
                return ResourceManager.GetString("TITLE_SCHEMA_OVERRIDES", resourceCulture);
            }
        }
    }
}
